apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d9dcpgu76-python
  janus-idp.io/tekton: d9dcpgu76-python
  backstage.io/kubernetes-id: d9dcpgu76-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d9dcpgu76-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
